name: CI/CD & Release Pipeline

on: 
  push:
    branches:
      - main
      - master
    
jobs:
  install-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Build Dependencies
        working-directory: ./framework/setup
        run: |
          sudo apt install python3-setuptools -y 
          sudo pip install . -v
          
      - name: Installation Successful
        run: echo "âœ… SDRForge setup completed successfully on the runner!"

  create-release:
    needs: install-test 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Copy pyproject.toml to Root
        run: |
          cp ./framework/setup/pyproject.toml ./pyproject.toml
          echo "pyproject.toml copied to root for release action."

      - name: Create Release from pyproject.toml Version
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version_from_toml: true 
          generate_release_notes: true 
          files: |
            setup.py
            ./framework/setup/pyproject.toml
